update help.c to fix security bug
sirdude/gurbalib pull request #38
Opened 2020-05-03 00:19 UTC by evilmog

path traversal in help.c allows administrative paths to be read

2020-05-03 16:46 UTC, sirdude requested changes
Sorry but this doesn't fix it right now it's declaring a var and then not setting it but checking it.
It also has some extra cruft, adds another unused var.

2020-05-03 17:10 UTC, evilmog commented
I'll update the pr, it was a rapid hack and worked, I might have copy and
pasted from the wrong branch

On Sun., May 3, 2020, 10:46 a.m. Kent Mein, <notifications@github.com>
wrote:

> *@sirdude* requested changes on this pull request.
>
> Sorry but this doesn't fix it right now it's declaring a var and then not
> setting it but checking it.
> It also has some extra cruft, adds another unused var.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/sirdude/gurbalib/pull/38#pullrequestreview-404636705>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAZBQUQNQ6ORLSERV3DSX53RPWNW5ANCNFSM4MX4XZOQ>
> .
>

2020-05-03 17:12 UTC, evilmog commented
Updated fix, sorry about that, please re-review

2020-05-05 00:19 UTC, evilmog reviewed
Review completed, fixes implemented (incomplete copy and paste), also added CVE-2020-12649 reference as assigned

2020-05-05 16:12 UTC, sirdude commented
Sorry this still doesn't work, it breaks help wiz/bootcamp for example.
I've put in a fix though.  Basically test to make sure we are in our subdir /docs/help before processing.

2020-05-05 16:12 UTC, closed without merging

2025-04-27 19:07 UTC, evilmog commented
For those reading this later, the fix was adding this in help.c
```
if (strcmp(file[0..9], "/doc/help/") != 0) {
    return;
}
```